apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-cicd-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-cicd-pipeline
  template:
    metadata:
      labels:
        app: flask-cicd-pipeline
    spec:
      containers:
      - name: flask-cicd-pipeline
        image: balaji783/flask-cicd-pipeline:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-cicd-pipeline-service
spec:
  type: NodePort
  selector:
    app: flask-cicd-pipeline
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30007

